output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = "${module.eks-demo-cluster.kubeconfig}"
}

output "iam_role_arn" {
  description = "arn of AWS iam EKS role for ALB ingress"
  value = "${module.eks-demo-cluster.cluster_iam_role_arn}"
}